version: '3' # устанавливается в отношении с версией docker-composer. Можно найти в таблице доки.  
services: # Описывает сервисы и инструкции к ним 
  node: # название сервиса. Может быть разным
    image: node # Определяет какой образ используется 
    ports: # определяет порты слева хост локально справа хост контейнера "HOST:CONTAINER" 
      - 8080:8080
    depends_on: # зависимости для сервиса. Cначало запускаються зависимости а потом сам сервис. 
      - database
    working_dir: /var/www/node # Место для рабочей папки. При запуске 
    volumes:
      - ./server/:/var/www/node
    command: bash -c "npm install && npm start"
  database:
    image: "mongo"
    volumes:
      - ./database:/data/db
  reactapp:
    image: node
    ports:
      - 3000:3000
    working_dir: /home/app
    volumes:
      - ./client:/home/app
    command: bash -c "npm install && npm start"